admin_index:
    path: /admin
    defaults:
        _controller: 'AppBundle:Admin/Products:index'

admin_edit:
    path: /admin/products/{id}
    defaults:
        _controller: 'AppBundle:Admin/Products:edit'
